apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "calculator.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      nodeSelector:
        workload: application

      initContainers:
        - name: wait-for-mysql
          image: busybox

          command:
            - sh
            - -c
            - |
              echo "Waiting for MySQL..."

              until nc -z mysql 3306
              do
                echo "MySQL not ready..."
                sleep 2
              done

              echo "MySQL Ready!"

      containers:
        - name: backend

          image: "{{ required "backend.image.repository is required" .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - containerPort: 5000

          resources:
{{ toYaml .Values.backend.resources | indent 12 }}

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10

          env:
            - name: APP_VERSION
              value: "v2"

            - name: DB_HOST
              value: mysql

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DATABASE
