apiVersion: v1
kind: ConfigMap

metadata:
  name: mysql-init-script
  namespace: {{ .Release.Namespace }}

data:

  init.sql: |
    CREATE TABLE IF NOT EXISTS history (
      id INT AUTO_INCREMENT PRIMARY KEY,
      num1 FLOAT,
      num2 FLOAT,
      operation VARCHAR(20),
      result FLOAT
    );
